//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurante
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class billy_jackEntities : DbContext
    {
        public billy_jackEntities()
            : base("name=billy_jackEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tabela_categoria> tabela_categoria { get; set; }
        public virtual DbSet<tabela_dados_pessoais> tabela_dados_pessoais { get; set; }
        public virtual DbSet<tabela_identificacao_produto> tabela_identificacao_produto { get; set; }
        public virtual DbSet<tabela_imagem> tabela_imagem { get; set; }
        public virtual DbSet<tabela_ingredientes> tabela_ingredientes { get; set; }
        public virtual DbSet<tabela_itens_produtos> tabela_itens_produtos { get; set; }
        public virtual DbSet<tabela_mesas> tabela_mesas { get; set; }
        public virtual DbSet<tabela_pedidos> tabela_pedidos { get; set; }
        public virtual DbSet<tabela_produto> tabela_produto { get; set; }
        public virtual DbSet<tabela_tipo_pessoa> tabela_tipo_pessoa { get; set; }
        public virtual DbSet<tabela_tipo_usuario> tabela_tipo_usuario { get; set; }
        public virtual DbSet<tabela_usuario> tabela_usuario { get; set; }
    }
}
