//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurante
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabela_ingredientes
    {
        public int id { get; set; }
        public int quantidade { get; set; }
        public decimal preco_venda { get; set; }
        public string nome_ingrediente { get; set; }
    }
}
