//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurante
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabela_identificacao_produto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tabela_identificacao_produto()
        {
            this.tabela_produto = new HashSet<tabela_produto>();
        }
    
        public int id { get; set; }
        public string referencia { get; set; }
        public string descricao { get; set; }
        public int id_categoria { get; set; }
        public string codbarras { get; set; }
        public int id_imagem { get; set; }
    
        public virtual tabela_categoria tabela_categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tabela_produto> tabela_produto { get; set; }
    }
}
