//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurante
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabela_pedidos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tabela_pedidos()
        {
            this.tabela_itens_produtos = new HashSet<tabela_itens_produtos>();
        }
    
        public int id { get; set; }
        public System.DateTime data { get; set; }
        public int id_mesa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tabela_itens_produtos> tabela_itens_produtos { get; set; }
        public virtual tabela_mesas tabela_mesas { get; set; }
    }
}
